export type ShowcaseProduct = {
  id: string;
  title: string;
  slug: string;
  category: "necklaces" | "earrings" | "bracelets" | "bags" | "gifts";
  categoryTitle: string;
  price: number;
  compareAtPrice?: number;
  rating: number;
  reviewCount: number;
  badge?: string;
  material: string;
  color: string;
  chainLength?: string;
  variantId: string;
  visual: string;
  description: string;
};

export const showcaseProducts: ShowcaseProduct[] = [
  {
    id: "p-heart",
    title: "گردنبند قلب مینیمال",
    slug: "minimal-necklace",
    category: "necklaces",
    categoryTitle: "گردنبند",
    price: 1390000,
    compareAtPrice: 1640000,
    rating: 4.8,
    reviewCount: 89,
    badge: "-۱۵٪",
    material: "استیل ضدحساسیت",
    color: "طلایی",
    chainLength: "۴۵ سانتی‌متر",
    variantId: "v-1",
    visual: "heart",
    description: "گردنبند قلب مینیمال با طراحی ظریف و مینیمال، نمادی از عشق و لطافت است.",
  },
  {
    id: "p-pearl-drop",
    title: "گردنبند مروارید اشکی",
    slug: "pearl-drop-necklace",
    category: "necklaces",
    categoryTitle: "گردنبند",
    price: 1232000,
    compareAtPrice: 1450000,
    rating: 4.7,
    reviewCount: 31,
    badge: "-۱۰٪",
    material: "برنج آبکاری",
    color: "طلایی",
    chainLength: "۴۰ سانتی‌متر",
    variantId: "v-pearldrop",
    visual: "pearl-drop",
    description: "آویز مروارید اشکی برای استایل‌های لطیف و هدیه‌های خاص.",
  },
  {
    id: "p-coin",
    title: "گردنبند سکه‌ای مینیمال",
    slug: "coin-necklace",
    category: "necklaces",
    categoryTitle: "گردنبند",
    price: 890000,
    rating: 4.6,
    reviewCount: 33,
    badge: "جدید",
    material: "استیل ضدحساسیت",
    color: "طلایی",
    chainLength: "۴۰ سانتی‌متر",
    variantId: "v-coin",
    visual: "coin",
    description: "گردنبند سکه‌ای با آویز ظریف برای استفاده روزمره.",
  },
  {
    id: "p-moon-star",
    title: "گردنبند دو لایه ماه و ستاره",
    slug: "moon-star-necklace",
    category: "necklaces",
    categoryTitle: "گردنبند",
    price: 1190000,
    rating: 4.9,
    reviewCount: 56,
    material: "استیل ۳۱۶",
    color: "طلایی",
    chainLength: "۴۵ سانتی‌متر",
    variantId: "v-moon",
    visual: "moon-star",
    description: "دو لایه ظریف با آویز ماه و ستاره برای استایل شبانه.",
  },
  {
    id: "p-pearl-ring",
    title: "گردنبند حلقه و مروارید",
    slug: "pearl-ring-necklace",
    category: "necklaces",
    categoryTitle: "گردنبند",
    price: 999000,
    rating: 4.8,
    reviewCount: 18,
    material: "برنج آبکاری",
    color: "طلایی",
    chainLength: "۴۵ سانتی‌متر",
    variantId: "v-pearlring",
    visual: "pearl-ring",
    description: "ترکیب حلقه طلایی و مروارید برای هدیه و مهمانی.",
  },
  {
    id: "p-letter",
    title: "گردنبند حروف M",
    slug: "letter-m-necklace",
    category: "necklaces",
    categoryTitle: "گردنبند",
    price: 790000,
    rating: 4.7,
    reviewCount: 34,
    badge: "جدید",
    material: "استیل ضدحساسیت",
    color: "طلایی",
    chainLength: "۴۵ سانتی‌متر",
    variantId: "v-letter",
    visual: "letter",
    description: "آویز حرف M با زنجیر ظریف برای استایل شخصی.",
  },
  {
    id: "p-plaque",
    title: "گردنبند پلاک مستطیل",
    slug: "rectangle-plaque-necklace",
    category: "necklaces",
    categoryTitle: "گردنبند",
    price: 949000,
    rating: 4.9,
    reviewCount: 14,
    material: "استیل ضدحساسیت",
    color: "طلایی",
    chainLength: "۵۰ سانتی‌متر",
    variantId: "v-plaque",
    visual: "plaque",
    description: "پلاک مستطیل با نقش کلاسیک و آبکاری براق.",
  },
  {
    id: "p-clover",
    title: "گردنبند ونکلیف",
    slug: "clover-necklace",
    category: "necklaces",
    categoryTitle: "گردنبند",
    price: 1299000,
    rating: 4.8,
    reviewCount: 39,
    material: "برنج آبکاری",
    color: "طلایی",
    chainLength: "۴۵ سانتی‌متر",
    variantId: "v-clover",
    visual: "clover",
    description: "طرح چهاربرگ لطیف برای استایل کلاسیک و زنانه.",
  },
  {
    id: "p-chain-bracelet",
    title: "دستبند زنجیری کارتیه",
    slug: "cartier-chain-bracelet",
    category: "bracelets",
    categoryTitle: "دستبند",
    price: 599000,
    rating: 4.6,
    reviewCount: 36,
    material: "برنج آبکاری",
    color: "طلایی",
    variantId: "v-bracelet",
    visual: "bracelet",
    description: "دستبند زنجیری طلایی برای استفاده روزمره.",
  },
  {
    id: "p-pearl-earrings",
    title: "گوشواره مروارید اشکی",
    slug: "pearl-earrings",
    category: "earrings",
    categoryTitle: "گوشواره",
    price: 720000,
    compareAtPrice: 850000,
    rating: 4.8,
    reviewCount: 102,
    badge: "۱۲٪",
    material: "مروارید مصنوعی",
    color: "طلایی",
    variantId: "v-2",
    visual: "earrings",
    description: "گوشواره مرواریدی کلاسیک با حلقه طلایی.",
  },
  {
    id: "p-link-earrings",
    title: "گوشواره حلقه‌ای زنجیری",
    slug: "chain-link-earrings",
    category: "earrings",
    categoryTitle: "گوشواره",
    price: 649000,
    rating: 4.7,
    reviewCount: 98,
    material: "استیل ضدحساسیت",
    color: "طلایی",
    variantId: "v-link-earrings",
    visual: "link-earrings",
    description: "گوشواره زنجیری مدرن با فرم کشیده.",
  },
  {
    id: "p-bag",
    title: "کیف دستی قهوه‌ای",
    slug: "brown-handbag",
    category: "bags",
    categoryTitle: "کیف",
    price: 1850000,
    rating: 4.5,
    reviewCount: 22,
    material: "چرم مصنوعی",
    color: "قهوه‌ای",
    variantId: "v-bag",
    visual: "bag",
    description: "کیف دستی قهوه‌ای با فرم کلاسیک و کاربردی.",
  },
];

export const categoryTiles = [
  { title: "کیف", slug: "bags", visual: "bag" },
  { title: "دستبند", slug: "bracelets", visual: "bracelet" },
  { title: "گوشواره", slug: "earrings", visual: "earrings" },
  { title: "گردنبند", slug: "necklaces", visual: "heart" },
  { title: "هدیه", slug: "gifts", visual: "gift" },
];

export function getShowcaseProduct(slug: string) {
  return showcaseProducts.find((product) => product.slug === slug);
}

export function getProductsByCategory(slug: string) {
  return showcaseProducts.filter((product) => product.category === slug);
}

