"use client";
import { FormEvent, useState } from "react";
import type { Banner, HomepageSection, SiteSetting } from "../lib/api";
import { createBanner, createHomepageSection, createSiteSetting, deleteBanner, deleteHomepageSection, updateBanner, updateHomepageSection, updateSiteSetting } from "../lib/api";

export function BannerManager({ initial }: { initial: Banner[] }) {
  const [items,setItems]=useState(initial); const [error,setError]=useState("");
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const d=new FormData(e.currentTarget);try{const item=await createBanner({title:String(d.get("title")),subtitle:String(d.get("subtitle")),external_url:String(d.get("external_url")),link_url:String(d.get("link_url")),placement:String(d.get("placement")),sort_order:Number(d.get("sort_order")),is_active:true});setItems(x=>[...x,item]);e.currentTarget.reset();}catch(err){setError(err instanceof Error?err.message:"خطا");}}
  return <div className="admin-stack"><form className="panel admin-form" onSubmit={create}><h2>بنر جدید</h2><div className="form-grid"><label>عنوان<input name="title" required/></label><label>زیرعنوان<input name="subtitle"/></label><label>جایگاه<input name="placement" defaultValue="home" required/></label><label>ترتیب<input name="sort_order" type="number" defaultValue="0"/></label><label>آدرس تصویر<input name="external_url" type="url" dir="ltr"/></label><label>لینک مقصد<input name="link_url" dir="ltr"/></label></div><button className="button">افزودن بنر</button>{error&&<p className="form-error">{error}</p>}</form><section className="panel"><h2>بنرهای فروشگاه</h2>{items.map(item=><div className="cms-row" key={item.id}>{item.image_url&&<img src={item.image_url} alt=""/>}<div><strong>{item.title}</strong><small>{item.placement}</small></div><label><input type="checkbox" checked={item.is_active} onChange={async e=>{const saved=await updateBanner(item.id,{is_active:e.target.checked});setItems(xs=>xs.map(x=>x.id===item.id?saved:x));}}/> فعال</label><button className="text-danger" onClick={async()=>{await deleteBanner(item.id);setItems(x=>x.filter(v=>v.id!==item.id));}}>حذف</button></div>)}</section></div>;
}

export function SettingsManager({ initialSections, initialSettings }: { initialSections: HomepageSection[]; initialSettings: SiteSetting[] }) {
  const [sections,setSections]=useState(initialSections);const [settings,setSettings]=useState(initialSettings);const [message,setMessage]=useState("");
  async function addSection(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);try{const section=await createHomepageSection({key:String(d.get("key")),kind:String(d.get("kind")),title:String(d.get("title")),subtitle:String(d.get("subtitle")),external_url:String(d.get("external_url")),link_text:String(d.get("link_text")),link_url:String(d.get("link_url")),config:{},sort_order:Number(d.get("sort_order")),is_active:true});setSections(x=>[...x,section]);e.currentTarget.reset();}catch(err){setMessage(err instanceof Error?err.message:"خطا");}}
  async function saveSetting(e:FormEvent<HTMLFormElement>,setting?:SiteSetting){e.preventDefault();const d=new FormData(e.currentTarget);let value:unknown=String(d.get("value"));try{value=JSON.parse(String(d.get("value")));}catch{}const saved=setting?await updateSiteSetting(setting.id,{label:String(d.get("label")),value,is_public:d.get("is_public")==="on"}):await createSiteSetting({key:String(d.get("key")),label:String(d.get("label")),value,is_public:d.get("is_public")==="on"});setSettings(xs=>setting?xs.map(x=>x.id===setting.id?saved:x):[...xs,saved]);setMessage("تنظیم ذخیره شد.");}
  return <div className="admin-stack"><section className="panel"><h2>بخش‌های صفحه اصلی</h2>{sections.map(s=><div className="cms-row" key={s.id}>{s.image_url&&<img src={s.image_url} alt=""/>}<div><strong>{s.title}</strong><small>{s.kind} · {s.key}</small></div><label><input type="checkbox" checked={s.is_active} onChange={async e=>{const saved=await updateHomepageSection(s.id,{is_active:e.target.checked});setSections(xs=>xs.map(x=>x.id===s.id?saved:x));}}/> فعال</label><button className="text-danger" onClick={async()=>{await deleteHomepageSection(s.id);setSections(xs=>xs.filter(x=>x.id!==s.id));}}>حذف</button></div>)}<form className="admin-form sub-form" onSubmit={addSection}><div className="form-grid"><label>کلید<input name="key" dir="ltr" required/></label><label>نوع<select name="kind"><option value="hero">Hero</option><option value="product_rail">محصولات</option><option value="category_grid">دسته‌بندی</option><option value="promo">پروموشن</option><option value="instagram">اینستاگرام</option></select></label><label>عنوان<input name="title" required/></label><label>زیرعنوان<input name="subtitle"/></label><label>تصویر<input name="external_url" type="url" dir="ltr"/></label><label>متن لینک<input name="link_text"/></label><label>لینک<input name="link_url" dir="ltr"/></label><label>ترتیب<input name="sort_order" type="number" defaultValue="0"/></label></div><button className="button">افزودن بخش</button></form></section>
    <section className="panel"><h2>فوتر و اطلاعات تماس</h2>{settings.map(setting=><form className="setting-row" key={setting.id} onSubmit={e=>saveSetting(e,setting)}><b dir="ltr">{setting.key}</b><input name="label" defaultValue={setting.label}/><textarea name="value" defaultValue={typeof setting.value==="string"?setting.value:JSON.stringify(setting.value,null,2)}/><label><input name="is_public" type="checkbox" defaultChecked={setting.is_public}/> عمومی</label><button>ذخیره</button></form>)}<form className="setting-row" onSubmit={e=>saveSetting(e)}><input name="key" dir="ltr" placeholder="کلید جدید" required/><input name="label" placeholder="عنوان" required/><textarea name="value" placeholder='{"phone":"..."}'/><label><input name="is_public" type="checkbox" defaultChecked/> عمومی</label><button className="button">افزودن</button></form>{message&&<p>{message}</p>}</section></div>;
}
