# Generated by Django 5.0.14 on 2026-07-14 13:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('hero', 'Hero'), ('product_rail', 'Product rail'), ('category_grid', 'Category grid'), ('promo', 'Promotion'), ('instagram', 'Instagram')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=320)),
                ('image', models.FileField(blank=True, null=True, upload_to='homepage/')),
                ('external_url', models.CharField(blank=True, max_length=600)),
                ('link_text', models.CharField(blank=True, max_length=100)),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('label', models.CharField(max_length=180)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='external_url',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
