# Generated by Django 5.0.14 on 2026-07-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='external_url',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.CheckConstraint(check=models.Q(('image__isnull', False), models.Q(('external_url', ''), _negated=True), _connector='OR'), name='product_image_has_file_or_url'),
        ),
    ]
