# Generated by Django 5.0.14 on 2026-07-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_request_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
